
  src_path: '/data/CRIME/src/'
  tar_path: '/data/CRIME/tar/'
  model_path: '/models/'
  result_path: '/results/'
  chck_path: '/chckpoints/'
  test_split: 0.20
  val_split: 0.25
  rand_state: 42 
  rand_state2: 84
  tuning_epochs: 1000
  tuning_trials: 400
  num_of_frozen_layers: 0
  storageN: 'sqlite:///dbs/CDB.db'
  stdy: 'crime'
  target_label: 'ViolentCrimesPerPop'
  test_samples: 
    - 0.1
    - 0.2
    - 0.3
  index_maker:
    module_name: 'index_maker'
    class_name: 'index_maker'
    init_arg: 100
  train_only:
    module_name: 'train_only'
    class_name: 'train_only'
    init_arg: 100
  source_only:
    module_name: 'source_only'
    class_name: 'source_only'
    init_arg: 100
  linear_probing:
    module_name: 'transfer_learning'
    class_name: 'transfer_learning'
    init_arg: 'linear_probing'
    num_of_frozen_layers:
      - 1
      - 2
      - 3
      - 20
  fine_tuning:
    module_name: 'transfer_learning'
    class_name: 'transfer_learning'
    init_arg: 'fine_tuning'
    num_of_frozen_layers:
      - 0
  k_regressor:
    module_name: 'k_regressor'
    class_name: 'k_regressor'
    init_arg: 2
  random_forrest:
    module_name: 'random_forrest'
    class_name: 'random_forrest'
    init_arg: 100
  stacked_model:
    module_name: 'stacked_model'
    class_name: 'stacked_model'
    init_arg: 2
  IPT:
    module_name: 'IPT'
    class_name: 'IPT'
    init_arg: 100 
    IPT_params:
      neurons: 100
      layers: 6
      lr: 0.01
  tasks:
  - transfer_learning
  - transfer_learning
  - value 3
  
  source_model: '/work2/08389/hcs77/stampede2/models/crime/crime-model.json'
  source_model_weights: '/work2/08389/hcs77/stampede2/models/crime/crime-model'
  source_model_params: '/work2/08389/hcs77/stampede2/results/txt/Source-model-on-target-crime-parameters.txt'
  source_model_prev_weights: '/work2/08389/hcs77/stampede2/models/x-crime-SourceModel'
