
  src_path: '/data/SKILLCRAFT/CASE2/src/'
  tar_path: '/data/SKILLCRAFT/CASE2/tar/3/'
  model_path: '/fslda/models/CASE2/'
  result_path: '/fslda/results/'
  csv_path: '/fslda/results/csv/skillcraft/CASE2/3/'
  indices_path: '/fslda/results/indices/skillcraft/3/'
  fig_path: '/fslda/results/figs/skillcraft/CASE2/3/'
  chck_path: '/fslda/chckpoints/'
  test_split: 0.20
  val_split: 0.25
  rand_state: 42 
  rand_state2: 84
  tuning_epochs: 1000
  tuning_trials: 400
  num_of_frozen_layers: 0
  storageN: 'sqlite:///dbs/SKILLCRAFT.db'
  stdy: 'skillcraft'
  target_label: 'ActionLatency'
  test_samples:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 1.00
  index_maker:
    module_name: 'index_maker'
    class_name: 'index_maker'
    init_arg: 3
  jay_test1:
    module_name: 'jay_test1'
    class_name: 'jay_test1'
    init_arg: 3
  train_only:
    module_name: 'train_only'
    class_name: 'train_only'
    init_arg: 100
  source_only:
    module_name: 'source_only'
    class_name: 'source_only'
    init_arg: 100
  target_only:
    module_name: 'target_only'
    class_name: 'target_only'
    init_arg: 10
  linear_probing:
    module_name: 'transfer_learning'
    class_name: 'transfer_learning'
    init_arg: 'linear_probing'
    num_of_frozen_layers:
      - 1
      - 2
      - 3
  fine_tuning:
    module_name: 'transfer_learning'
    class_name: 'transfer_learning'
    init_arg: 'fine_tuning'
    num_of_frozen_layers:
      - 0
  TransferIPT:
    init_arg: 'fine_tuning'
    module_name: 'TransferIPT'
    class_name: 'TransferIPT'
    IPT_params:
      neurons: 100
      layers: 6
      lr: 0.01
    linear_probing:
      num_of_frozen_layers:
        - 1
        - 2
        - 3
    fine_tuning:
      num_of_frozen_layers:
        - 0
  k_regressor:
    module_name: 'k_regressor'
    class_name: 'k_regressor'
    init_arg: 2
  random_forrest:
    module_name: 'random_forrest'
    class_name: 'random_forrest'
    init_arg: 100
  stacked_model:
    module_name: 'stacked_model'
    class_name: 'stacked_model'
    init_arg: 2
  IPT:
    module_name: 'IPT'
    class_name: 'IPT'
    init_arg: 100 
    IPT_params:
      neurons: 100
      layers: 6
      lr: 0.01
  KIPT:
    init_arg: 'fine_tuning'
    module_name: 'KIPT'
    class_name: 'KIPT'
    IPT_params:
      neurons: 100
      layers: 6
      lr: 0.01
    linear_probing:
      num_of_frozen_layers:
        - 1
        - 2
        - 3
    fine_tuning:
      num_of_frozen_layers:
        - 0
  res_ipt:
    init_arg: 'fine_tuning'
    module_name: 'res_ipt'
    class_name: 'res_ipt'
    IPT_params:
      neurons: 100
      layers: 6
      lr: 0.01
    linear_probing:
      num_of_frozen_layers:
        - 1
        - 2
        - 3
  nUIPT:
    init_arg: 'fine_tuning'
    module_name: 'nUIPT'
    class_name: 'nUIPT'
    IPT_params:
      neurons: 100
      layers: 4
      lr: 0.001
    second_model_params:
      neurons: 100
      nol: 4
      lr: 0.001
      moment: 0.98
    combined_model_params:
      neurons: 5
      nol: 4
      lr: 0.001
      moment: 0.98
    linear_probing:
      num_of_frozen_layers:
        - 1
        - 2
        - 3
  stacked_ipt:
    module_name: 'stacked_ipt'
    class_name: 'stacked_ipt'
    init_arg: 100
    IPT_params:
      neurons: 100
      layers: 6
      lr: 0.01
  tasks:
  - transfer_learning
  - transfer_learning
  - value 3
  
  source_model: '/models/skillcraft/CASE2/1/skillcraft-model.json'
  source_model_weights: '/models/skillcraft/CASE2/1/skillcraft-model'
  source_model_params: '/fslda/results/txt/Source-model-on-target-skillcraft-parameters.txt'
  source_model_prev_weights: '/models/x-skillcraft-SourceModel'
