
  src_path: '/data/SKILLCRAFT/APM/src/'
  tar_path: '/data/SKILLCRAFT/APM/tar/3/'
  model_path: '/NP/models/'
  result_path: '/NP/results/'
  csv_path: '/NP/results/csv/skillcraft/3/APM/'
  indices_path: '/NP/results/indices/skillcraft/3/'
  fig_path: '/NP/results/figs/skillcraft/3/'
  chck_path: '/NP/chckpoints/'
  test_split: 0.20
  val_split: 0.25
  rand_state: 42 
  rand_state2: 84
  tuning_epochs: 1000
  tuning_trials: 400
  num_of_frozen_layers: 0
  storageN: 'sqlite:///dbs/SKILLCRAFT.db'
  stdy: 'skillcraft'
  target_label: 'ActionLatency'
  target_app: 'skillcraft'
  test_samples:
    - 0.1
  index_maker:
    module_name: 'index_maker'
    class_name: 'index_maker'
    init_arg: 3
  jay_test1:
    module_name: 'jay_test1'
    class_name: 'jay_test1'
    init_arg: 6
  caller:
    module_name: 'caller'
    class_name: 'caller'
    init_arg: 10
    list_of_classes:
      - 'Bagging'
      - 'SVR'
      - 'DecisionTree'
      - 'XGBoost'
      - 'nn'
      - 'Transformer'
    list_of_class_args:
      - 10
      - 10
      - 10
      - 10
      - "/NP/yaml/skillcraft-config-3_APM.yaml"
      - "/NP/yaml/skillcraft-config-3_APM.yaml"

  remask_caller:
    module_name: 'remask_caller'
    class_name: 'remask_caller'
    init_arg: 10
    list_of_classes:
      - 'Bagging'
      - 'SVR'
      - 'DecisionTree'
      - 'XGBoost'
      - 'nn'
      - 'Transformer'
    list_of_class_args:
      - 10
      - 10
      - 10
      - 10
      - "/NP/yaml/skillcraft-config-3_APM.yaml"
      - "/NP/yaml/skillcraft-config-3_APM.yaml"

  class_caller:
    module_name: 'class_caller'
    class_name: 'class_caller'
    init_arg: 10
    list_of_classes:
      - 'Bagging'
      - 'SVR'
      - 'DecisionTree'
      - 'XGBoost'
      - 'nn'
      - 'Transformer'
    list_of_class_args:
      - 10
      - 10
      - 10
      - 10
      - "/NP/yaml/skillcraft-config-3_APM.yaml"
      - "/NP/yaml/skillcraft-config-3_APM.yaml"
  hyper_impute_caller:
    module_name: 'hyper_impute_caller'
    class_name: 'hyper_impute_caller'
    feature_name: 'APM'
    init_arg: 10
    list_of_classes:
      - 'Bagging'
      - 'SVR'
      - 'DecisionTree'
      - 'XGBoost'
      - 'nn'
      - 'Transformer'
    list_of_class_args:
      - 10
      - 10
      - 10
      - 10
      - "/NP/yaml/skillcraft-config-6.yaml"
      - "/NP/yaml/skillcraft-config-6.yaml"
  train_only:
    module_name: 'train_only'
    class_name: 'train_only'
    init_arg: 100
  source_only:
    module_name: 'source_only'
    class_name: 'source_only'
    init_arg: 100
  target_only:
    module_name: 'target_only'
    class_name: 'target_only'
    init_arg: 10
  linear_probing:
    module_name: 'transfer_learning'
    class_name: 'transfer_learning'
    init_arg: 'linear_probing'
    num_of_frozen_layers:
      - 1
      - 2
      - 3
  fine_tuning:
    module_name: 'transfer_learning'
    class_name: 'transfer_learning'
    init_arg: 'fine_tuning'
    num_of_frozen_layers:
      - 0
  TransferIPT:
    init_arg: 'fine_tuning'
    module_name: 'TransferIPT'
    class_name: 'TransferIPT'
    IPT_params:
      neurons: 100
      layers: 6
      lr: 0.01
    linear_probing:
      num_of_frozen_layers:
        - 1
        - 2
        - 3
    fine_tuning:
      num_of_frozen_layers:
        - 0
  k_regressor:
    module_name: 'k_regressor'
    class_name: 'k_regressor'
    init_arg: 2
  random_forrest:
    module_name: 'random_forrest'
    class_name: 'random_forrest'
    init_arg: 100
  stacked_model:
    module_name: 'stacked_model'
    class_name: 'stacked_model'
    init_arg: 2
  IPT:
    module_name: 'IPT'
    class_name: 'IPT'
    init_arg: 100 
    IPT_params:
      neurons: 100
      layers: 6
      lr: 0.01
  IPT2:
    module_name: 'IPT2'
    class_name: 'IPT2'
    init_arg: 100
    IPT_params:
      neurons: 100
      layers: 6
      lr: 0.01
  KIPT:
    init_arg: 'fine_tuning'
    module_name: 'KIPT'
    class_name: 'KIPT'
    IPT_params:
      neurons: 100
      layers: 6
      lr: 0.01
    linear_probing:
      num_of_frozen_layers:
        - 1
        - 2
        - 3
    fine_tuning:
      num_of_frozen_layers:
        - 0
  stacked_ipt:
    module_name: 'stacked_ipt'
    class_name: 'stacked_ipt'
    init_arg: 100
    IPT_params:
      neurons: 100
      layers: 6
      lr: 0.01
  res_ipt:
    init_arg: 'fine_tuning'
    module_name: 'res_ipt'
    class_name: 'res_ipt'
    IPT_params:
      neurons: 100
      layers: 6
      lr: 0.01
    linear_probing:
      num_of_frozen_layers:
        - 1
        - 2
        - 3


  tasks:
  - transfer_learning
  - transfer_learning
  - value 3
  
  source_model: '/models/NP/skillcraft/1/skillcraft-model.json'
  source_model_weights: '/models/NP/skillcraft/1/skillcraft-model'
  source_model_params: '/fslda/results/txt/Source-model-on-target-skillcraft-parameters.txt'
  source_model_prev_weights: '/models/x-skillcraft-SourceModel'
